# Site settings
title: Willian Justen - Desenvolvedor Front End
description: A blog about lorem ipsum dolor sit amet
baseurl: "/cards-jekyll-template" # the subpath of your site, e.g. /blog
url: "https://jingyu91.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: jingyu
user_description: Anon Developer at Lorem Ipsum Dolor
email: jingyu91@naver.com
twitter_username: jingyu
github_username:  jingyu91
gplus_username:  jingyu
disqus_username: jingyu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
